### PR TITLE
Update proguard-custom.txt

### PR DESCRIPTION
**Pull request by AadityaDev**
webview code added for ionic

### CODE REVIEW

**Comment by greybax** [comment]
@AadityaDev could you please add more description to this PR. Why do we need to keep class for the ionic framework?

**Comment by greybax** [comment]
@AadityaDev ping

**Comment by greybax** [comment]
@AadityaDev please clarify your changes, Otherwise, I will have to close this PR

**Comment by AadityaDev** [comment]
Hi @greybax ,

These are the webview classes needed to initialize cordova webview in android.
Let me know if you want a more detailed description

**Pull request closed without merging**
