### PR TITLE
match package.json

### PR DESCRIPTION
**Pull request by rodrigograca31**

### CODE REVIEW

**Comment by greybax** [comment]
Thank you for PR! Merged

**Comment by rodrigograca31** [comment]
Great! 
(Even though I can't use this plugin yet, app crashes..... :joy:)

**Comment by greybax** [comment]
Do we need revert?

**Comment by rodrigograca31** [comment]
> Do we need revert?

nooooo, ignore what I said. :joy: its a separate issue....

**Comment by greybax** [comment]
@rodrigograca31 create another issue?

**Pull request merged**
